import type { Metadata } from 'next'
 
export const metadata: Metadata = {
  title: 'My Portfolio',
}
 
export default function Page() {
  return (
    <div>
      <>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/favicon.ico" />
      </>
      <main></main>
    </div>
  );
}