import type { Metadata } from 'next'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { 
  AiFillLinkedin, 
  AiFillTwitterCircle, 
  AiFillMail, 
  AiFillGithub
} from 'react-icons/ai';
import Image from 'next/image';
import kathy from '../public/kathy-rowe.jpg';
import web1 from '../public/web1.png'

export const metadata: Metadata = {
  title: 'Kathy Rowe Portfolio',
}
 
export default function Page() {
  return (
    <div>
      <>
        <title>Kathy Rowe Portfolio</title>
        <meta name='description' content='Generated by create-next-app' />
        <link rel='icon' href='/favicon.ico' />
      </>
      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>Kathy Rowe</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-blue-600 text-white px-4 py-2 rounded-md ml-8' href='https://www.overleaf.com/latex/templates/jakes-resume/syzfjbzwjncs'>
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className='flex justify-center items-center min-h-[65vh]'>
            <div className='text-left p-10'>
              <h2 className='text-xl py-2 text-blue-600 font-semibold'>KATHY ROWE</h2>
              <h3 className='text-3xl py-2 text-gray-800 font-black'>28th President of William & Mary 👋</h3>
              <p className='text-md py-5 text-gray-800'>
                Nationally recognized as an innovator in higher education, <br />
                I champion the liberal arts, entrepreneurship and <br />
                strengthening education-workforce pathways. <br />
              </p>
              <div className='text-5xl flex justify-center gap-16 py-3 text-gray-800'>
                <a href='https://www.linkedin.com/in/katherine-rowe-2a711545'><AiFillLinkedin /></a>
                <a href='https://x.com/williamandmary'><AiFillTwitterCircle /></a>
                <a href='https://www.github.com/gdscwm'><AiFillGithub /></a>
                <a href='mailto:president@wm.edu'><AiFillMail /></a>
              </div>
            </div>
            <div className='bg-gradient-to-b from-blue-600 rounded-full w-80 h-80 relative overflow-hidden'>
              <Image src={kathy} alt='profile_pic' layout='fill' objectFit='cover' />
            </div>
          </div>
        </section>
        <section className='flex justify-center items-center min-h-screen'>
          <div className='flex flex-col items-start space-y-4 p-6 bg-white rounded-lg w-full max-w-4xl'>
            <h3 className='text-lg text-blue-600 font-bold'>EDUCATION</h3>
            <div className='flex justify-between w-full h-auto'>
              <p className='text-lg font-semibold'>
                College of William and Mary
              </p>
              <p className='text-sm text-gray-800 font-bold text-right'>
                MAY 2026
              </p>
            </div>
            <div>
              <div className='flex flex-col space-y-2'>
                <p className='text-m text-gray-600 italic'>
                  Bachelor's of Science in Computer Science
                </p>
                <p className='text-sm text-gray-600'>
                  Coursework: Computational Problem Solving, Calculus II
                </p>
              </div>
            </div>
            <div className='flex justify-between w-full h-auto'>
              <p className='text-lg font-semibold'>
                Random High School
              </p>
              <p className='text-sm text-gray-800 font-bold text-right'>
                MAY 2022
              </p>
            </div>
            <div className='flex justify-between w-full'>
              <div className='flex flex-col space-y-2'>
                <p className='text-m text-gray-600 italic'>
                  High School Diploma
                </p>
                <p className='text-sm text-gray-600'>
                  Coursework: AP Computer Science A, CS Programming, Web Page Development, Calculus II
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className='flex justify-center items-center min-h-screen'>
          <div className='flex flex-col items-start space-y-4 p-6 bg-white rounded-lg w-full max-w-4xl'>
            <h3 className='text-lg text-blue-600 font-bold'>EXPERIENCE</h3>
            <div className='flex justify-between w-full h-auto'>
              <p className='text-lg font-semibold'>
                Target
              </p>
              <p className='text-sm text-gray-800 font-bold text-right'>
                SEP 2021 – AUG 2026
              </p>
            </div>
            <div className='flex justify-between w-full'>
              <div className='flex flex-col space-y-2'>
                <p className='text-sm text-gray-600 italic'>
                  Guest Advocate, Cart/Store Attendant
                </p>
                <ul className='list-disc list-inside space-y-2 text-gray-600'> 
                  <li className='text-sm text-gray-600'>
                    Enhanced guest experience by welcoming, thanking, and exceeding service expectations.
                  </li>
                  <li className='text-sm text-gray-600'>
                    Focused on guest interaction and effective resolution of service issues.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className='flex justify-center items-center min-h-screen'>
          <div className='flex flex-col items-start space-y-4 p-6 bg-white rounded-lg w-full max-w-4xl'>
            <h3 className='text-lg text-blue-600 font-bold'>PROJECTS</h3>
            <h3 className='text-m text-blue-600 font-bold'>Portfolio Website</h3>
            <Image src={web1} alt='Portfolio website visual' />
          </div>
        </section>
      </main>
    </div>
  );
}
